### Request JSON:
http://localhost:3000/hello
Content-Type: application/json

{
  "name": "Alex"
}

### Response:
# http://localhost:3000/hello
#
#{"message":"Hello, Alex!"}

### Request Form:
http://localhost:3000/hello
Content-Type: application/x-www-form-urlencoded

name=Alex

### Response:
# http://localhost:3000/hello
#
#{"message":"Hello, Alex!"}

